# -*- coding: utf-8 -*-
"""sincarpetasano.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WYOAvOB48gZADHtjd0hLLVlI741M939e
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras.preprocessing import image
from google.colab import drive

# Montar Google Drive para acceder a las carpetas originales
drive.mount('/content/drive')

import tensorflow as tf
from tensorflow.keras import layers
import os

# Define las rutas a tus carpetas originales de los 6 defectos
ruta_train = '/content/drive/MyDrive/archive2/NEU-DET/train/images'
ruta_val = '/content/drive/MyDrive/archive2/NEU-DET/validation/images'

BATCH_SIZE = 16 #Va a estar dando imágenes en paquetes de 16
IMG_SIZE = (224, 224)#MovileNetV2 trabaja con imágenes de 224*224 por lo que esta linea redimensiona las imágenes

print("Cargando dataset original de 6 defectos...")
train_ds = tf.keras.utils.image_dataset_from_directory(
    ruta_train,
    shuffle=True,
    batch_size=BATCH_SIZE,
    image_size=IMG_SIZE
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    ruta_val,
    shuffle=False,
    batch_size=BATCH_SIZE,
    image_size=IMG_SIZE
)

class_names = train_ds.class_names
print(f"\n Clases detectadas (6 defectos): {class_names}")

from tensorflow.keras import layers

#  Cargar el extractor base MobileNetV2 preentrenado con ImageNet
base_model = tf.keras.applications.MobileNetV2(
    input_shape=(224, 224, 3),
    include_top=False,
    weights='imagenet'
)

#  Congelar los pesos del modelo base para Transfer Learning
base_model.trainable = False

#  Construir la topología de SteelSense AI (6 Defectos)
inputs = tf.keras.Input(shape=(224, 224, 3))

# Capa de reescalado explícita: Mapea píxeles de [0, 255] a [-1, 1] internamente
x = layers.Rescaling(scale=1./127.5, offset=-1.0)(inputs)

# Pasar datos por el extractor convolucional
x = base_model(x, training=False)

# Reducción de dimensionalidad y regularización para evitar sobreajuste
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dropout(0.2)(x)

# Capa de salida: 6 neuronas (una por defecto) con activación Softmax
outputs = layers.Dense(6, activation='softmax')(x)

# Unificar todo en la arquitectura final
model = tf.keras.Model(inputs, outputs)

# 4. Compilación del modelo
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

EPOCHS = 15

print("Iniciando el entrenamiento de SteelSense AI (Modo Taxonomía de Defectos)...")
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS
)
print("\n¡Entrenamiento multiclase completado con éxito!")

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']
epochs_range = range(len(acc))

plt.figure(figsize=(14, 6))

# Gráfica de Precisión (Accuracy)
plt.subplot(1, 2, 1)
plt.plot(epochs_range, acc, label='Entrenamiento', linewidth=2, color='blue')
plt.plot(epochs_range, val_acc, label='Validación', linewidth=2, color='orange')
plt.title('Precisión del Modelo (Accuracy)', fontsize=14, fontweight='bold')
plt.xlabel('Épocas', fontsize=12)
plt.ylabel('Valor de Precisión (0-1)', fontsize=12)
plt.legend(loc='lower right')
plt.grid(True, linestyle='--', alpha=0.6)

# Gráfica de Pérdida (Loss)
plt.subplot(1, 2, 2)
plt.plot(epochs_range, loss, label='Entrenamiento', linewidth=2, color='blue')
plt.plot(epochs_range, val_loss, label='Validación', linewidth=2, color='orange')
plt.title('Pérdida del Modelo (Loss)', fontsize=14, fontweight='bold')
plt.xlabel('Épocas', fontsize=12)
plt.ylabel('Costo / Error', fontsize=12)
plt.legend(loc='upper right')
plt.grid(True, linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, classification_report

y_true = []
y_pred = []

print("Calculando predicciones de validación...")
for images, labels in val_ds:
    preds = model.predict(images, verbose=0)
    y_true.extend(labels.numpy())
    y_pred.extend(np.argmax(preds, axis=1))

# Construir matriz de confusión
cm = confusion_matrix(y_true, y_pred)

# Graficar Heatmap elegante
plt.figure(figsize=(9, 7))
sns.heatmap(cm, annot=True, fmt='d', cmap='Oranges', xticklabels=class_names, yticklabels=class_names)
plt.xlabel('Predicción del Modelo', fontsize=12)
plt.ylabel('Defecto Real (Ground Truth)', fontsize=12)
plt.title('Matriz de Confusión Multiclase - SteelSense AI', fontsize=14, fontweight='bold')
plt.show()

# Imprimir reporte formal con Precision, Recall y F1-Score
print("\nReporte de Clasificación Industrial:")
print(classification_report(y_true, y_pred, target_names=class_names))

ruta_guardado = '/content/drive/MyDrive/SteelSense_Model_6Clasesprueba.keras'
model.save(ruta_guardado)
print(f"✅ ¡Modelo multiclase guardado con éxito en: {ruta_guardado}!")